const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),money=n=>'¥'+Number(n).toLocaleString('zh-CN',{minimumFractionDigits:2,maximumFractionDigits:2});
const key='maliu-demo-v15',regionNames=['四川 · 成都','湖南 · 长沙','湖北 · 武汉','贵州 · 贵阳','江西 · 南昌','安徽 · 合肥'],gameNames=['血战到底','长沙麻将','红中麻将','跑得快'];
const seed={regions:regionNames.map((name,i)=>({id:'R'+i,name,wechat:'demo_region_'+i,status:'启用'})),managers:Array.from({length:3},(_,i)=>({id:'M'+i,name:['成都长沙负责人','武汉贵阳负责人','南昌合肥负责人'][i],account:'demo_manager_'+i,gameId:'DEMO-M'+i,regions:['R'+i*2,'R'+(i*2+1)],status:'启用'})),services:[{id:'S0',name:'总部客服示例一',account:'demo_hq_support',gameId:'DEMO-S0',type:'总部客服',region:'all',rate:3,status:'启用'},...regionNames.map((_,i)=>({id:'S'+(i+1),name:'区域客服示例'+(i+1),account:'demo_support_'+i,gameId:'DEMO-S'+(i+1),type:'区域客服',region:'R'+i,rate:0,status:'启用'}))],agents:[],tea:[],players:[],charges:[],rooms:[],transfers:[],logs:[]};
for(let i=0;i<24;i++){const region='R'+i%6,id='A'+(1001+i),company=i%3===0;seed.agents.push({id,name:'演示推广代理 '+(i+1),account:'demo_agent_'+(i+1),gameId:'DEMO-'+(8001+i),region,creator:company?'总部客服示例一':'区域客服示例'+(i%6+1),company,service:company?'S0':'S'+(i%6+1),status:'启用',quota:5,tier:'演示标准档',cards:100+i*12});for(let t=0;t<2;t++)seed.tea.push({id:'T'+(i*2+t+1),name:'演示茶馆 '+(i*2+t+1),agent:id,region,status:'营业中'});}
for(let i=0;i<60;i++)seed.players.push({id:'P'+(9001+i),name:'演示牌友 '+(i+1),tea:['T'+(i%48+1),'T'+((i+9)%48+1)],status:'正常'});
for(let day=0;day<30;day++){const date=new Date(Date.UTC(2026,9,10-day)).toISOString().slice(0,10);for(let i=0;i<12;i++){const a=seed.agents[(day*3+i)%24],tea=seed.tea.filter(t=>t.agent===a.id)[i%2];seed.rooms.push({id:'G'+day+'-'+i,date,region:a.region,agent:a.id,tea:tea.id,game:gameNames[i%4],players:[0,1,2,3].map(n=>'P'+(9001+(day*7+i*3+n)%60)),status:i===10?'已解散':i===11&&day%3===0?'异常':'已结算',rounds:i===10?2:8,cards:i===10?0:4});if(i<8){const refunded=i===2&&day%4===0?30:0;seed.charges.push({id:'C'+day+'-'+i,date,refundDate:refunded?date:'',region:a.region,agent:a.id,tea:i%3===0?'':tea.id,player:'P'+(9001+(day*7+i*3)%60),amount:(i+1)*30,refunded,service:a.service,rate:a.service==='S0'?3:0,company:a.company,status:'成功'});}}}
seed.transfers=seed.agents.map((a,i)=>({id:'F'+(i+1),date:'2026-10-10',region:a.region,agent:a.id,gameId:a.gameId,from:'演示系统账户',to:a.account,cards:100+i*12,operator:'演示历史导入',remark:'仅查询历史，不提供转卡操作'}));
let db;try{db=JSON.parse(localStorage.getItem(key))||structuredClone(seed);if(!db.managers)db=structuredClone(seed)}catch{db=structuredClone(seed)}
let role='hq',page='overview',account='HQ',selected=[],start='2026-10-04',end='2026-10-10',query='',offset=0,exportRows=[],timer;
const roles={hq:'总公司',service:'总部客服',regional:'地区负责人',local:'区域客服'},groups=[['工作空间',['overview','regions']],['账号管理',['managers','agents','services','contacts']],['游戏管理',['gamestats','daily','rooms','tea','players']],['资金查询',['recharges','refunds','partnerstats','cards','transfers','rewards']],['系统设置',['settings','logs','permissions']]],labels={overview:'经营总览',regions:'区域管理',managers:'地区负责人',agents:'普通推广代理',services:'客服管理',contacts:'区域联系方式',gamestats:'游戏统计',daily:'区域日活',rooms:'房间与对局',tea:'茶馆管理',players:'玩家查询',recharges:'充值流水',refunds:'退款明细',partnerstats:'负责人业绩汇总',cards:'房卡余额',transfers:'转卡流水',rewards:'客服奖励',settings:'个人密码',logs:'操作记录',permissions:'权限说明'};
const rn=id=>db.regions.find(r=>r.id===id)?.name||'未知区域',an=id=>db.agents.find(a=>a.id===id)?.name||id,sn=id=>db.services.find(s=>s.id===id)?.name||'总部服务';
const allowed=()=>role==='regional'?(db.managers.find(m=>m.id===account&&m.status==='启用')?.regions||[]):role==='local'?[db.services.find(s=>s.id===account&&s.status==='启用')?.region].filter(Boolean):db.regions.map(r=>r.id),scope=()=>allowed().filter(id=>!selected.length||selected.includes(id)),currentAgent=a=>scope().includes(a.region)&&(role!=='service'||(a.service==='S0'&&db.services.find(s=>s.id==='S0')?.status==='启用'));
const eventVisible=e=>scope().includes(e.region)&&(role!=='service'||(db.services.find(s=>s.id==='S0')?.status==='启用'&&db.agents.find(a=>a.id===e.agent)?.service==='S0')),dated=e=>e.date>=start&&e.date<=end,charges=()=>db.charges.filter(e=>eventVisible(e)&&dated(e)),refunds=()=>db.charges.filter(e=>e.refunded&&eventVisible(e)&&e.refundDate>=start&&e.refundDate<=end),rooms=()=>db.rooms.filter(e=>eventVisible(e)&&dated(e)),sum=(xs,k)=>xs.reduce((s,x)=>s+Number(x[k]||0),0),uniq=xs=>new Set(xs).size;
function stats(r){const c=charges().filter(e=>!r||e.region===r),f=refunds().filter(e=>!r||e.region===r),g=rooms().filter(e=>(!r||e.region===r)&&e.status==='已结算');return {net:sum(c,'amount')-sum(f,'refunded'),paid:sum(c,'amount'),refund:sum(f,'refunded'),active:uniq(g.flatMap(e=>e.players)),tea:uniq(g.map(e=>e.tea)),cards:sum(g,'cards'),games:g.length,dissolved:rooms().filter(e=>(!r||e.region===r)&&e.status==='已解散').length};}
const canOpenService=()=>['hq','regional'].includes(role),permitted=p=>!(p==='managers'&&role!=='hq')&&!(p==='regions'&&role!=='hq')&&!(p==='rewards'&&!['hq','service'].includes(role))&&!(p==='services'&&!canOpenService());
function notify(s){$('#toast').textContent=s;$('#toast').style.display='block';clearTimeout(timer);timer=setTimeout(()=>$('#toast').style.display='none',3500)}
function save(action,regions=scope()){db.logs.unshift({time:new Date().toLocaleString('zh-CN'),actor:roles[role],account,action,regions:[...regions]});try{localStorage.setItem(key,JSON.stringify(db))}catch{notify('当前浏览器无法保存，刷新会丢失修改')}render();}
function heading(title,desc,actions=''){return `<div class="heading"><div><div class="eyebrow">MALIU / OPERATIONS · V1.5</div><h1>${title}</h1><p>${desc}</p></div><div class="actions">${actions}</div></div>`;}
function controls(search=true){return `<section class="scope-panel"><fieldset><legend>区域范围 <small>默认汇总全部授权区域；勾选可缩小范围</small></legend>${allowed().map(id=>`<label><input type="checkbox" data-scope="${id}" ${selected.includes(id)?'checked':''}>${esc(rn(id))}</label>`).join('')||'<span>当前账号没有授权区域</span>'}<button id="all-scope" class="text-button" onclick="clearScope()">全部授权区域</button></fieldset><div class="toolbar"><label for="start">开始日期</label><input type="date" id="start" value="${start}" max="${end}"><label for="end">结束日期</label><input type="date" id="end" value="${end}" min="${start}"><button onclick="setPeriod(7)" data-days="7">最近7天</button><button onclick="setPeriod(30)" data-days="30">最近30天</button>${search?`<div class="search-box"><input type="search" id="search" aria-label="搜索当前列表" value="${esc(query)}" placeholder="名称、游戏ID、流水号"><button onclick="clearSearch()" id="clear">清空</button></div>`:''}</div></section>`;}
function table(headers,data){const rows=data.filter(r=>r.some(c=>String(c).toLowerCase().includes(query.toLowerCase())));exportRows=[headers.filter(h=>h!=='操作'),...rows.map(r=>r.filter((_,i)=>headers[i]!=='操作').map(c=>String(c).replace(/<[^>]*>/g,'')))];offset=Math.min(offset,Math.max(0,Math.ceil(rows.length/8)-1));return `<section class="panel"><div class="table-wrap"><table><thead><tr>${headers.map(h=>`<th scope="col">${h}</th>`).join('')}</tr></thead><tbody>${rows.slice(offset*8,offset*8+8).map(r=>`<tr>${r.map(c=>`<td>${c}</td>`).join('')}</tr>`).join('')||`<tr><td class="empty" colspan="${headers.length}">当前条件没有记录，请调整日期、区域或关键词。</td></tr>`}</tbody></table></div><div class="pagination"><span>共 ${rows.length} 条 · 第 ${offset+1} / ${Math.max(1,Math.ceil(rows.length/8))} 页</span><div><button data-paging="-1" ${!offset?'disabled':''}>上一页</button><button data-paging="1" ${(offset+1)*8>=rows.length?'disabled':''}>下一页</button></div></div></section>`;}
const canExport=()=>role==='hq'?['overview','gamestats','daily','rooms','tea','recharges','refunds','partnerstats','cards','transfers','rewards'].includes(page):role==='regional'?['overview','gamestats','daily','tea','partnerstats'].includes(page):role==='service'?['overview','partnerstats','rewards'].includes(page):false;
const act=(id,action,label)=>`<button class="text-button" data-action="${action}" data-id="${esc(id)}">${label}</button>`;
function overview(){const s=stats(),days=Array.from({length:7},(_,i)=>new Date(Date.UTC(2026,9,4+i)).toISOString().slice(0,10)).filter(d=>d>=start&&d<=end),values=days.map(d=>sum(charges().filter(c=>c.date===d),'amount')-sum(refunds().filter(c=>c.refundDate===d),'refunded')),max=Math.max(1,...values),points=values.map((v,i)=>`${45+i*500/Math.max(1,values.length-1)},${165-v/max*130}`).join(' ');return heading('所有负责区域，一处掌握','经营、游戏与账号在同一工作台汇总。示例数据截至 2026-10-10。','<button id="export">↓ 导出区域汇总</button>')+controls(false)+`<div class="stats">${[['净充值业绩',money(s.net),'成功实付 − 当期成功退款'],['对局活跃玩家',s.active,'跨区域汇总按玩家编号去重'],['有效房间',s.games,'完成并结算的房间'],['消耗房卡',s.cards,'与充值金额分开统计']].map(([label,value,note])=>`<section class="stat"><div class="stat-label">${label}</div><div class="stat-value">${value}</div><div class="stat-foot">${note}</div></section>`).join('')}</div><div class="charts"><section class="panel"><div class="panel-head"><div><h2>近7天净充值趋势</h2><small>所选区域与日期的演示记录聚合</small></div><span class="badge">人民币 元</span></div><div class="chart"><svg viewBox="0 0 600 190" role="img" aria-label="近7天净充值趋势">${[35,100,165].map(y=>`<path d="M40 ${y}H580" stroke="#e1e8e4"/>`).join('')}<polyline points="${points}" stroke="#16765e" stroke-width="3" fill="none"/>${values.map((v,i)=>`<circle cx="${45+i*500/Math.max(1,values.length-1)}" cy="${165-v/max*130}" r="4" fill="#16765e"><title>${days[i]}：${money(v)}</title></circle>`).join('')}</svg><div class="chart-labels">${days.map(d=>`<span>${d.slice(5)}</span>`).join('')}</div></div></section><section class="panel"><div class="panel-head"><div><h2>玩法活跃分布</h2><small>按有效房间数量计算</small></div><span class="badge">4 种玩法</span></div>${gameNames.map(n=>{const count=rooms().filter(g=>g.game===n&&g.status==='已结算').length,p=s.games?count/s.games*100:0;return `<div class="game-row"><div><span>${n}</span><strong>${count} 场 · ${p.toFixed(1)}%</strong></div><div class="bar"><i style="width:${p}%"></i></div></div>`}).join('')}</section></div>`+table(['区域','地区负责人','实付充值','成功退款','净业绩','对局活跃','有效房间','解散房间'],scope().map(r=>{const t=stats(r);return [rn(r),esc(db.managers.find(m=>m.regions.includes(r)&&m.status==='启用')?.name||'未分配'),money(t.paid),money(t.refund),money(t.net),t.active,t.games,t.dissolved]}));}
function listing(){let headers=[],data=[],desc='当前授权范围内的查询结果；全部数据均为虚构示例。',actions='<button id="export">↓ 导出当前查询</button>';const agents=db.agents.filter(currentAgent);
 if(page==='agents'){desc='开户来源、经营区域、服务客服与业绩归属分别记录，普通代理不拥有本后台登录权。';actions=act('','create-agent','＋ 开设普通代理')+actions;headers=['账号 / 游戏ID','代理名称','当前区域','开户来源','服务客服','业绩归属','茶馆上限 / 档位','状态','操作'];data=agents.map(a=>[`${esc(a.account)}<small>${a.gameId} · ${a.id}</small>`,esc(a.name),rn(a.region),esc(a.creator),esc(sn(a.service)),a.company?'公司':'经营区域',`${a.quota} / ${esc(a.tier)}`,a.status,act(a.id,'detail-agent','详情')+(role==='hq'?act(a.id,'edit-agent','资料设置')+act(a.id,'move','迁区')+act(a.id,'bind','服务分配')+act(a.id,'toggle-agent',a.status==='启用'?'停用':'启用'):'')]);}
 if(page==='managers'){desc='同一账号可负责多个区域；每个区域只分配给一位启用中的地区负责人。';actions=act('','create-manager','＋ 开设地区负责人')+actions;headers=['账号 / 游戏ID','负责人','授权区域','状态','操作'];data=db.managers.map(m=>[`${m.account}<small>${m.gameId}</small>`,esc(m.name),m.regions.map(rn).join('、'),m.status,act(m.id,'assign','分配区域')]);}
 if(page==='services'){desc='地区负责人包含区域客服开户职责；区域客服只能在绑定区域开户。';actions=act('','create-service','＋ 开设客服')+actions;headers=['账号 / 游戏ID','名称','类型','区域','当前奖励比例','状态','操作'];data=db.services.filter(s=>role==='hq'||scope().includes(s.region)).map(s=>[`${esc(s.account)}<small>${esc(s.gameId)}</small>`,esc(s.name),s.type,s.region==='all'?'全区域开户':rn(s.region),s.type==='总部客服'?`${s.rate}%${s.pendingRate!==undefined?'<small>次日生效：'+s.pendingRate+'%</small>':''}`:'—',s.status,role==='hq'?(s.type==='总部客服'?act(s.id,'rate','奖励比例'):'')+act(s.id,'toggle-service',s.status==='启用'?'停用':'启用'):'只读']);}
 if(page==='regions'||page==='contacts'){desc='区域状态和客服微信由总部配置，多区域汇总不合并各区联系方式。';headers=['区域编号','区域','地区负责人','客服微信','状态','操作'];data=db.regions.filter(r=>scope().includes(r.id)).map(r=>[r.id,r.name,esc(db.managers.find(m=>m.regions.includes(r.id)&&m.status==='启用')?.name||'未分配'),esc(r.wechat),r.status,role==='hq'?act(r.id,'wechat','修改微信')+act(r.id,'toggle-region',r.status==='启用'?'停用':'启用'):'只读']);}
 if(page==='tea'){desc='茶馆只读；无法关联茶馆的充值保留在代理未关联金额，不按茶馆数量分摊。';headers=['茶馆','当前区域','普通代理','有效房间','活跃玩家','净充值业绩','状态','操作'];data=db.tea.filter(t=>scope().includes(t.region)&&agents.some(a=>a.id===t.agent)).map(t=>{const g=rooms().filter(r=>r.tea===t.id&&r.status==='已结算');return [esc(t.name)+'<small>'+t.id+'</small>',rn(t.region),esc(an(t.agent)),g.length,uniq(g.flatMap(g=>g.players)),money(sum(charges().filter(c=>c.tea===t.id),'amount')-sum(refunds().filter(c=>c.tea===t.id),'refunded')),t.status,act(t.id,'detail-tea','详情')]});}
 if(page==='players'){desc='玩家可加入多个茶馆、跨区参与；只展示可见茶馆关系，不提供资产修改或封禁。';headers=['昵称 / 游戏ID','可见茶馆关系','参与有效房间','状态','操作'];data=db.players.filter(p=>p.tea.some(id=>db.tea.some(t=>t.id===id&&scope().includes(t.region)&&agents.some(a=>a.id===t.agent)))).map(p=>[esc(p.name)+'<small>'+p.id+'</small>',p.tea.filter(id=>db.tea.some(t=>t.id===id&&scope().includes(t.region)&&agents.some(a=>a.id===t.agent))).join('、'),rooms().filter(g=>g.status==='已结算'&&g.players.includes(p.id)).length,p.status,act(p.id,'detail-player','详情')]);}
 if(page==='gamestats'){desc='有效房间、实际局数、房卡消耗及解散房间分开统计，异常不混入有效对局。';headers=['区域','玩法','有效房间','已结算局数','消耗房卡','解散房间','异常房间'];data=scope().flatMap(r=>gameNames.map(game=>{const g=rooms().filter(e=>e.region===r&&e.game===game),ok=g.filter(e=>e.status==='已结算');return [rn(r),game,ok.length,sum(ok,'rounds'),sum(ok,'cards'),g.filter(e=>e.status==='已解散').length,g.filter(e=>e.status==='异常').length]}));}
 if(page==='daily'){desc='区域日活是当天参加有效对局的去重玩家，各区相加不等于全平台去重人数。';headers=['日期','区域','对局活跃玩家','有效房间','活跃茶馆'];data=[...new Set(rooms().map(r=>r.date))].sort().reverse().flatMap(date=>scope().map(r=>{const g=rooms().filter(e=>e.date===date&&e.region===r&&e.status==='已结算');return [date,rn(r),uniq(g.flatMap(g=>g.players)),g.length,uniq(g.map(g=>g.tea))]}));}
 if(page==='rooms'){desc='查询房间、玩法、区域、茶馆、参与者及结算状态，不提供强制解散或补发房卡。';headers=['房间编号','日期','事件区域','茶馆','玩法','状态','局数','房卡','操作'];data=rooms().map(g=>[g.id,g.date,rn(g.region),g.tea,g.game,g.status,g.rounds,g.cards,act(g.id,'detail-room','详情')]);}
 if(page==='recharges'){desc='成功实付订单，沿用发生时区域、代理和茶馆快照。';headers=['流水号','日期','玩家游戏ID','实付金额','普通代理','事件区域','关联茶馆','操作'];data=charges().map(c=>[c.id,c.date,c.player,money(c.amount),esc(an(c.agent)),rn(c.region),c.tea||'未关联茶馆',act(c.id,'detail-charge','详情')]);}
 if(page==='refunds'){desc='按成功退款日扣减业绩，沿用原订单快照和原计奖比例。';headers=['退款流水','退款日期','原订单','事件区域','退款金额','奖励扣回','状态'];data=refunds().map(c=>['REF-'+c.id,c.refundDate,c.id,rn(c.region),money(c.refunded),money(c.refunded*c.rate/100),'成功']);}
 if(page==='partnerstats'){desc='按事件区域归集，公司与区域归属金额分别列示，不表示收益分配。';headers=['事件区域','地区负责人','实付充值','退款','净业绩','归公司净额','归区域净额','未关联茶馆净额'];data=scope().map(r=>{const c=charges().filter(c=>c.region===r),f=refunds().filter(c=>c.region===r),s=stats(r);return [rn(r),esc(db.managers.find(m=>m.regions.includes(r)&&m.status==='启用')?.name||'未分配'),money(s.paid),money(s.refund),money(s.net),money(sum(c.filter(c=>c.company),'amount')-sum(f.filter(c=>c.company),'refunded')),money(sum(c.filter(c=>!c.company),'amount')-sum(f.filter(c=>!c.company),'refunded')),money(sum(c.filter(c=>!c.tea),'amount')-sum(f.filter(c=>!c.tea),'refunded'))]});}
 if(page==='cards'){desc='原系统房卡余额查询，所有身份均无转卡、赠卡、扣卡或调账入口。';headers=['代理账号','名称','游戏ID','当前区域','持卡数量'];data=agents.map(a=>[esc(a.account),esc(a.name),a.gameId,rn(a.region),a.cards]);}
 if(page==='transfers'){desc='只读历史流水；原系统接口须限制地区负责人及区域客服转卡权限。';headers=['流水号','时间','转出账户','转入账户','游戏ID','房卡数','操作人','备注'];data=db.transfers.filter(t=>eventVisible(t)&&dated(t)).map(t=>[t.id,t.date,t.from,t.to,t.gameId,t.cards,t.operator,t.remark]);}
 if(page==='rewards'){desc='仅计奖、明细与对账，不打款；比例0–20%，两位小数，次日生效。';headers=['订单','日期','客服','计奖充值','原比例','应计奖励','退款扣回','净奖励'];data=db.charges.filter(c=>c.rate>0&&dated(c)&&scope().includes(c.region)&&(role==='hq'||c.service==='S0')).map(c=>[c.id,c.date,sn(c.service),money(c.amount),c.rate+'%',money(c.amount*c.rate/100),money((c.refundDate>=start&&c.refundDate<=end)?c.refunded*c.rate/100:0),money((c.amount-((c.refundDate>=start&&c.refundDate<=end)?c.refunded:0))*c.rate/100)]);}
 if(page==='logs'){desc='记录本浏览器修改；负责人仅看授权区域记录，客服仅看本人操作。';headers=['时间','操作者','范围','操作'];data=db.logs.filter(l=>role==='hq'||(['service','local'].includes(role)?l.actor===roles[role]&&l.account===account:l.regions.length&&l.regions.every(r=>scope().includes(r)))).map(l=>[l.time,l.actor,l.regions.map(rn).join('、'),esc(l.action)]);}
 return heading(labels[page],desc,actions)+controls()+table(headers,data);}
function permissions(){return heading('权限与业务说明','截图称谓“代理”对应地区负责人；普通推广代理是另一类业务对象。')+`<section class="panel policy"><h2>一次登录，汇总多个授权区域</h2><p>地区负责人默认查看全部负责区域，可筛选一个或多个；区域客服为部分职责，只绑定一个区域。普通推广代理没有本运营后台的独立登录权。</p><h2>关键边界</h2><ul><li>总部负责负责人分区、迁区、联系方式、充值档位及奖励配置。</li><li>地区负责人可在授权区域开普通代理和区域客服；区域客服仅在绑定区域开普通代理。</li><li>总部与总部客服开户业绩归公司；地区负责人和区域客服开户归经营区域。服务客服独立记录。</li><li>代理及茶馆迁区，历史流水、对局、奖励保留事件快照。总部客服绑定跨区保留，区域客服改由目标区客服或总部承接。</li><li>所有身份均只查余额和转卡流水。地区负责人及区域客服不得给下级转卡。</li><li>茶馆、玩家、充值退款、对局只读；代理资料和档位由总部维护。</li></ul><h2>演示环境</h2><p>静态交互原型，身份切换用于体验，未连接真实登录、游戏、支付、客服微信、结算或开户接口。公开页面不具备生产安全授权能力。请勿输入真实资料或密码。</p><button id="reset">恢复初始演示数据</button></section>`;}
function settings(){return heading('个人密码','正式系统校验原密码；公开演示不收集或保存密码。')+`<section class="panel policy"><h2>个人账户安全</h2><p>正式后台提供原密码、新密码和确认密码；禁止查询或导出密码。重置通过一次性凭据交接，日志不记录密码正文。</p><p>演示环境关闭密码输入，避免真实凭据进入公开原型。</p>${act('','password-info','查看密码流程')}</section>`;}
function render(){selected=selected.filter(r=>allowed().includes(r));if(!permitted(page))page='overview';$('#nav').innerHTML=groups.map(([group,ps])=>`<div class="nav-label">${group}</div>${ps.filter(permitted).map(p=>`<button onclick="navigatePage(this.dataset.page)" data-page="${p}" class="${page===p?'active':''}" aria-current="${page===p?'page':'false'}" title="${labels[p]}"><span class="icon" aria-hidden="true">${{overview:'◫',regions:'⌘',agents:'♙',tea:'▤',players:'♧',services:'☏'}[p]||'◇'}</span><span class="name">${labels[p]}</span></button>`).join('')}`).join('');$('#role').value=role;$('#crumb').textContent=labels[page];$('#main').innerHTML=`<div class="mobile-nav"><label for="mobile-page">功能导航</label><select id="mobile-page">${Object.keys(labels).filter(permitted).map(p=>`<option value="${p}" ${p===page?'selected':''}>${labels[p]}</option>`).join('')}</select></div><div class="notice"><strong>${roles[role]}视角</strong>${role==='service'?'可全区域开户，仅查询当前本人服务代理的数据。':'当前授权 '+allowed().length+' 个区域，汇总按玩家编号去重。'}<span class="scope-signature">${scope().map(rn).join(' / ')||'无授权区域'}</span>${['regional','local'].includes(role)?`<label for="demo-account">示例账号</label><select id="demo-account">${(role==='regional'?db.managers:db.services.filter(s=>s.type==='区域客服')).map(m=>`<option value="${m.id}" ${m.id===account?'selected':''}>${esc(m.name)}</option>`).join('')}</select>`:''}</div>`+(page==='overview'?overview():page==='permissions'?permissions():page==='settings'?settings():listing());const u=new URL(location.href);u.search=new URLSearchParams({page,role,account,regions:selected.join(','),start,end,v:'1.5'});history.replaceState(null,'',u);bind();}
function modal(title,body,onSave){const d=$('#dialog'),trigger=document.activeElement;d.innerHTML=`<form id="modal-form" novalidate><div class="dialog-head"><h2 id="dialog-title">${title}</h2><button type="button" id="close" aria-label="关闭弹窗">×</button></div><div class="dialog-body">${body}<div id="form-error" role="alert" class="error"></div></div><div class="dialog-foot"><button type="button" id="cancel">${onSave?'取消':'关闭'}</button>${onSave?'<button class="primary" type="submit">保存演示修改</button>':''}</div></form>`;let dirty=false;$('#modal-form').oninput=()=>dirty=true;const cancel=()=>{if(dirty&&onSave&&!confirm('放弃未保存的修改？'))return;d.close();trigger?.focus()};$('#cancel').onclick=$('#close').onclick=cancel;d.oncancel=e=>{e.preventDefault();cancel()};$('#modal-form').onsubmit=e=>{e.preventDefault();onSave?.(new FormData(e.target),d)};d.showModal();}
function invalid(id,s){$('#form-error').textContent=s;const f=$('#'+id);f?.setAttribute('aria-invalid','true');f?.setAttribute('aria-describedby','form-error');f?.focus();}
const field=(id,label,value='',type='text')=>`<label for="${id}">${label}</label><input id="${id}" name="${id}" type="${type}" value="${esc(value)}" maxlength="40">`;
function regionField(){return `<label for="new-region">经营区域</label><select id="new-region" name="region">${allowed().filter(id=>db.regions.find(r=>r.id===id).status==='启用').map(id=>`<option value="${id}">${rn(id)}</option>`).join('')}</select>`;}
function action(type,id){const a=db.agents.find(a=>a.id===id),s=db.services.find(s=>s.id===id),r=db.regions.find(r=>r.id===id),m=db.managers.find(m=>m.id===id);
 if(type.startsWith('detail-')){let obj=type==='detail-agent'?db.agents.filter(currentAgent).find(a=>a.id===id):type==='detail-tea'?db.tea.find(t=>t.id===id&&scope().includes(t.region)):type==='detail-player'?db.players.find(p=>p.id===id):type==='detail-room'?rooms().find(g=>g.id===id):charges().find(c=>c.id===id);if(!obj)return;const safe=structuredClone(obj);if(type==='detail-player')safe.tea=safe.tea.filter(t=>db.tea.some(x=>x.id===t&&scope().includes(x.region)&&db.agents.some(a=>currentAgent(a)&&a.id===x.agent)));const names={id:'编号',name:'名称',region:'区域',agent:'普通代理',tea:'茶馆',account:'登录账号',gameId:'游戏ID',company:'业绩归公司',service:'服务客服',quota:'茶馆上限',tier:'充值档位',cards:'房卡',players:'参与玩家',date:'日期',rate:'原奖励比例',amount:'实付金额',refunded:'退款金额',creator:'开户来源',status:'状态',game:'玩法',rounds:'局数',refundDate:'退款日期',player:'玩家游戏ID'};return modal('资料详情',`<div class="detail-grid">${Object.entries(safe).map(([k,v])=>`<div><small>${names[k]||k}</small>${esc(k==='region'?rn(v):k==='service'?sn(v):Array.isArray(v)?v.join('、'):v)}</div>`).join('')}</div>`,null);}
 if(type.startsWith('create-')){const kind=type.slice(7);if(kind==='manager'&&role!=='hq'||kind==='service'&&!canOpenService())return;return modal('开设'+({agent:'普通推广代理',service:'客服',manager:'地区负责人'}[kind]),field('new-name','名称')+field('new-account','登录账号（演示）')+field('new-game','游戏ID（演示）')+(kind==='manager'?'<p>开户后由总部分配一个或多个区域。</p>':regionField())+(kind==='service'&&role==='hq'?'<label for="new-type">客服类型</label><select id="new-type" name="type"><option>区域客服</option><option>总部客服</option></select>':'')+'<p class="muted">不接真实开户，勿填真实资料。普通代理不取得本后台登录权。</p>',(f,d)=>{const name=f.get('new-name').trim(),acc=f.get('new-account').trim(),gameId=f.get('new-game').trim(),region=f.get('region');if(!name)return invalid('new-name','请输入名称');if(!/^[a-zA-Z][a-zA-Z0-9_]{3,39}$/.test(acc))return invalid('new-account','账号须4–40位，以字母开头，仅字母数字下划线');if(!/^[a-zA-Z0-9_-]{3,40}$/.test(gameId))return invalid('new-game','游戏ID须3–40位字母、数字、下划线或连字符');if([...db.agents,...db.services,...db.managers].some(x=>x.account===acc||x.gameId===gameId))return invalid('new-account','账号或游戏ID已存在');if(kind!=='manager'&&(!allowed().includes(region)||db.regions.find(r=>r.id===region)?.status!=='启用'))return invalid('new-region','请选择启用的授权区域');const base={id:(kind==='agent'?'A':kind==='service'?'S':'M')+Date.now(),name,account:acc,gameId,status:'启用'};if(kind==='agent'){const company=['hq','service'].includes(role);db.agents.unshift({...base,region,creator:roles[role],company,service:role==='service'?'S0':role==='local'?account:role==='regional'?db.services.find(s=>s.region===region&&s.status==='启用')?.id||'':'',quota:5,tier:'演示标准档',cards:0})}else if(kind==='service')db.services.unshift({...base,type:f.get('type')||'区域客服',region:f.get('type')==='总部客服'?'all':region,rate:0});else db.managers.unshift({...base,regions:[]});d.close();save('开设'+name,region?[region]:[]);notify('演示账号已开设')});}
 if(type==='assign'&&role==='hq')return modal('分配负责人授权区域',`<p>${esc(m.name)}。已归其他负责人的区域需先从原负责人移除。</p><fieldset><legend>授权区域</legend>${db.regions.map(r=>{const other=db.managers.find(x=>x.id!==m.id&&x.status==='启用'&&x.regions.includes(r.id));return `<label><input type="checkbox" name="assigned" value="${r.id}" ${m.regions.includes(r.id)?'checked':''} ${other?'disabled':''}>${r.name}${other?'（'+esc(other.name)+'）':''}</label>`}).join('')}</fieldset>`,(f,d)=>{const rs=f.getAll('assigned');if(rs.some(r=>db.managers.some(x=>x.id!==m.id&&x.status==='启用'&&x.regions.includes(r))))return invalid('','区域已经分配');const before=[...m.regions];m.regions=rs;d.close();save('调整 '+m.name+' 授权：'+before.map(rn).join('、')+' → '+rs.map(rn).join('、'),[...new Set([...before,...rs])]);notify('授权区域已更新')});
 if(type==='move'&&role==='hq')return modal('普通代理及茶馆迁区',`<p>${esc(a.name)} · 当前 ${rn(a.region)}</p>${regionField()}<p>茶馆随代理迁移。历史订单、对局、奖励保留快照；区域客服改为目标区客服或总部服务。</p>`,(f,d)=>{const next=f.get('region');if(!allowed().includes(next)||db.regions.find(r=>r.id===next)?.status!=='启用')return invalid('new-region','目标区域不可用');const prev=a.region;if(next===prev)return invalid('new-region','请选择不同区域');a.region=next;db.tea.filter(t=>t.agent===a.id).forEach(t=>t.region=next);if(db.services.find(s=>s.id===a.service)?.type!=='总部客服')a.service=db.services.find(s=>s.type==='区域客服'&&s.region===next&&s.status==='启用')?.id||'';d.close();save('代理 '+a.name+' 及茶馆迁区：'+rn(prev)+' → '+rn(next),[prev,next]);notify('当前关系已迁区；历史归属保持不变')});
 if(type==='bind'&&role==='hq')return modal('分配服务客服',`<p>${esc(a.name)} · ${rn(a.region)}</p><label for="binding">服务客服</label><select id="binding" name="binding"><option value="">总部临时服务</option>${db.services.filter(s=>s.status==='启用'&&(s.type==='总部客服'||s.region===a.region)).map(s=>`<option value="${s.id}" ${a.service===s.id?'selected':''}>${esc(s.name)}</option>`).join('')}</select><p>改绑不改开户来源、归属和历史计奖快照。</p>`,(f,d)=>{a.service=f.get('binding');d.close();save('调整 '+a.name+' 服务客服',[a.region]);notify('服务绑定已更新')});
 if(type==='edit-agent'&&role==='hq')return modal('代理资料与额度设置',field('agent-name','名称',a.name)+field('quota','茶馆最大数量',a.quota,'number')+'<label for="tier">充值档位引用</label><select id="tier" name="tier"><option>演示标准档</option><option>演示合作档</option></select><p>档位为虚构引用，实际价格和支付规则由原系统提供；不修改余额。</p>',(f,d)=>{const n=f.get('agent-name').trim(),q=Number(f.get('quota'));if(!n)return invalid('agent-name','请输入名称');if(f.get('quota')===''||!Number.isInteger(q)||q<0||q>999)return invalid('quota','请输入0–999整数');if(q<db.tea.filter(t=>t.agent===a.id).length)return invalid('quota','上限不能低于已有茶馆数');a.name=n;a.quota=q;a.tier=f.get('tier');d.close();save('修改 '+a.name+' 资料、茶馆上限及档位',[a.region]);notify('配置已更新')});
 if(type==='wechat'&&role==='hq')return modal('设置区域客服微信',field('wechat','微信号',r.wechat)+'<p>每区域一个主要微信号，外部展示需原系统接入。</p>',(f,d)=>{const v=f.get('wechat').trim();if(!/^[a-zA-Z][a-zA-Z0-9_-]{5,29}$/.test(v))return invalid('wechat','请输入6–30位，以字母开头的微信号');r.wechat=v;d.close();save('修改 '+r.name+' 微信',[r.id]);notify('演示联系方式已保存')});
 if(type==='rate'&&role==='hq')return modal('总部客服奖励比例',field('rate','次日起生效的比例（0–20%）',s.pendingRate??s.rate,'number')+'<p>最多两位小数。演示保存待生效配置，不改写历史计奖。</p>',(f,d)=>{const raw=f.get('rate'),v=Number(raw);if(!/^\d+(\.\d{1,2})?$/.test(raw)||v>20||v<0)return invalid('rate','请输入0–20之间、最多两位小数的比例');s.pendingRate=v;d.close();save('设置 '+s.name+' 次日起奖励 '+v+'%');notify('比例已保存，历史计奖保持不变')});
 if(type.startsWith('toggle-')&&role==='hq'){const obj=a||s||r;if(!obj)return;return modal('确认'+(obj.status==='启用'?'停用':'启用'),`<p>${esc(obj.name)}。停用不删除历史；区域停用不默认关闭玩家或游戏。客服停用后当前服务交总部临时承接。</p>`,(f,d)=>{obj.status=obj.status==='启用'?'停用':'启用';if(s&&s.status==='停用')db.agents.filter(a=>a.service===s.id).forEach(a=>a.service='');d.close();save(obj.status+' '+obj.name,r?[r.id]:a?[a.region]:scope());notify('演示状态已更新')});}
 if(type==='password-info')return modal('个人密码流程','<p>正式系统：原密码、新密码、确认密码 → 服务端校验 → 修改成功重新登录。</p><p>重置通过一次性凭据交接，日志不记录密码。演示不收集密码。</p>',null);
}
function bind(){$('#mobile-page')?.addEventListener('change',e=>{page=e.target.value;query='';offset=0;render()});document.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>{page=b.dataset.page;query='';offset=0;render()});document.querySelectorAll('[data-scope]').forEach(b=>b.onchange=()=>{selected=[...document.querySelectorAll('[data-scope]:checked')].map(x=>x.dataset.scope);offset=0;render()});$('#all-scope')?.addEventListener('click',()=>{selected=[];offset=0;render()});$('#demo-account')?.addEventListener('change',e=>{account=e.target.value;selected=[];query='';offset=0;render()});for(const id of ['start','end'])$('#'+id)?.addEventListener('change',e=>{if(!e.target.value)return;if(id==='start')start=e.target.value;else end=e.target.value;if(start>end){notify('开始日期不能晚于结束日期');if(id==='start')start=end;else end=start}offset=0;render()});document.querySelectorAll('[data-days]').forEach(b=>b.onclick=()=>{end='2026-10-10';start=new Date(Date.UTC(2026,9,11-Number(b.dataset.days))).toISOString().slice(0,10);offset=0;render()});const search=()=>{query=$('#search').value;offset=0;render();$('#search').focus()};$('#search')?.addEventListener('input',e=>{if(!e.isComposing)search()});$('#search')?.addEventListener('compositionend',search);$('#clear')?.addEventListener('click',()=>{query='';offset=0;render();$('#search').focus()});document.querySelectorAll('[data-paging]').forEach(b=>b.onclick=()=>{offset+=Number(b.dataset.paging);render()});document.querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>action(b.dataset.action,b.dataset.id));$('#reset')?.addEventListener('click',()=>modal('恢复演示数据','<p>清除本浏览器修改，恢复虚构示例。</p>',(f,d)=>{db=structuredClone(seed);localStorage.removeItem(key);selected=[];d.close();render();notify('已恢复示例')}));$('#export')?.addEventListener('click',()=>{if(!canExport())return;const safe=v=>{v=String(v);if(/^[=+\-@\t\r]/.test(v))v="'"+v;return '"'+v.replace(/"/g,'""')+'"'};const csv='\uFEFF'+exportRows.map(r=>r.map(safe).join(',')).join('\r\n'),u=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'})),a=document.createElement('a');a.href=u;a.download=labels[page]+'_演示.csv';a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);notify('已导出当前条件全部记录')});if(!canExport())$('#export')?.remove();}
$('#role').onchange=e=>{role=e.target.value;account=role==='regional'?'M0':role==='local'?'S1':'HQ';selected=[];query='';offset=0;render();notify('已切换至'+roles[role])};
function loadURL(){const p=new URLSearchParams(location.search);role=Object.hasOwn(roles,p.get('role'))?p.get('role'):'hq';page=Object.hasOwn(labels,p.get('page'))?p.get('page'):'overview';account=p.get('account')||(role==='regional'?'M0':role==='local'?'S1':'HQ');if(role==='regional'&&!db.managers.some(m=>m.id===account))account='M0';if(role==='local'&&!db.services.some(s=>s.type==='区域客服'&&s.id===account))account='S1';selected=(p.get('regions')||'').split(',').filter(Boolean);if(/^\d{4}-\d{2}-\d{2}$/.test(p.get('start')||''))start=p.get('start');if(/^\d{4}-\d{2}-\d{2}$/.test(p.get('end')||''))end=p.get('end');if(start>end)start=end;render();}
window.addEventListener('popstate',loadURL);loadURL();

function clearScope(){selected=[];offset=0;render()}
function navigatePage(p){page=p;query='';offset=0;render()}

function setPeriod(days){end='2026-10-10';start=new Date(Date.UTC(2026,9,11-days)).toISOString().slice(0,10);offset=0;render()}
function clearSearch(){query='';offset=0;render();$('#search')?.focus()}
