// V1.6 service and operational workflows. Fixtures only; no network requests.
const extensionLabels=['analysis','tickets','announcements','messages','tasks','alerts','sync','access','config'];
const actorId=()=>role==='service'?'S0':role==='local'?account:role==='regional'?account:'HQ';
const actorName=()=>role==='hq'?'总公司演示账号':role==='regional'?db.managers.find(m=>m.id===account)?.name||roles[role]:sn(actorId());
const extensionSeed={tickets:seed.agents.slice(0,12).map((a,i)=>({id:'TK'+(1001+i),title:['开户资料核对','充值订单查询','房间解散疑问'][i%3],description:'虚构服务问题，请核查关联记录并补充处理意见。',region:a.region,agent:a.id,owner:a.service,creator:'HQ',date:'2026-10-'+String(10-i%5).padStart(2,'0'),status:['待分配','处理中','待补充','已解决'][i%4],priority:i%3===0?'紧急':'普通',comments:[]})),announcements:[{id:'N1',title:'演示后台服务时间说明',body:'客服工作时间为09:00至18:00。本页面仅展示虚构通知，不向外部渠道发送。',regions:regionNames.map((_,i)=>'R'+i),creator:'HQ',date:'2026-10-10',status:'已发布',version:1},{id:'N2',title:'区域服务流程更新草稿',body:'开户资料请先核对游戏ID，发现重复账号请联系总部核实。',regions:['R0','R1'],creator:'M0',date:'2026-10-10',status:'草稿',version:1}],messages:[],tasks:[{id:'JOB1',name:'经营日报摘要导出',owner:'HQ',regions:['R0','R1'],date:'2026-10-10',status:'已完成',count:2,note:'演示任务记录，下载请使用经营页面真实CSV导出入口。'},{id:'JOB2',name:'存量账号导入预检',owner:'HQ',regions:['R2'],date:'2026-10-10',status:'预检失败',count:0,note:'第3行游戏ID重复，修正后建立新批次。'},{id:'JOB3',name:'授权区域游戏摘要导出',owner:'M0',regions:['R0','R1'],date:'2026-10-09',status:'已完成',count:8,note:'虚构历史任务，未生成文件。'}],read:[],ack:[],config:{serviceHours:'09:00–18:00',responseHours:24,resolveDays:3,lowRooms:5},access:['HQ','M0','M1','M2','S0','S1','S2','S3'].map((owner,i)=>({id:'LOGIN'+i,owner,date:'2026-10-10',time:'2026-10-10 '+(9+i)+':10',result:i===7?'失败':'成功',device:i%2?'Chrome / Windows':'Edge / Windows',source:'演示脱敏来源',reason:i===7?'凭据校验失败':'—'}))};
Object.assign(seed,structuredClone(extensionSeed));
for(const [k,v] of Object.entries(extensionSeed))if(db[k]===undefined)db[k]=structuredClone(v);
const extDate=()=> '2026-10-10';
const nextTicketStates=t=>({待分配:['待分配','处理中'],处理中:['处理中','待补充','已解决'],待补充:['待补充','处理中','已解决'],已解决:['已解决','已关闭','处理中'],已关闭:['已关闭','处理中']}[t.status]||[]);
const ticketVisible=t=>scope().includes(t.region)&&(role==='hq'||role==='regional'||((t.owner===actorId()||t.creator===actorId())&&db.agents.some(a=>a.id===t.agent&&(role==='service'?a.service==='S0':a.region===db.services.find(s=>s.id===actorId())?.region))));
const announcementVisible=n=>n.regions.some(r=>scope().includes(r))&&(n.status==='已发布'||n.creator===actorId()||role==='hq');
const extAgentVisible=a=>currentAgent(a);
const ownedTask=t=>(role==='hq'||t.owner===actorId())&&t.regions.every(r=>scope().includes(r));
const extText=(id,label,value='',max=2000)=>`<label for="${id}">${label}</label><textarea id="${id}" name="${id}" maxlength="${max}" rows="5" style="resize:none">${esc(value)}</textarea>`;
const extRegionSelect=()=>`<label for="ext-region">区域</label><select id="ext-region" name="ext-region">${scope().filter(r=>db.regions.find(x=>x.id===r)?.status==='启用').map(r=>`<option value="${r}">${rn(r)}</option>`).join('')}</select>`;
function extensionPage(){
 if(page==='analysis')return analysisPage();
 let headers=[],rows=[],actions='',desc='新增建议模块 · 全部为虚构数据，不接入真实服务。';
 if(page==='tickets'){desc='内部服务工单：新建、分配、回复和状态流转；不包含即时聊天或退款执行。';actions=act('','create-ticket','＋ 新建工单');headers=['工单编号','标题 / 优先级','日期','区域','关联代理','受理客服','状态','操作'];rows=db.tickets.filter(t=>ticketVisible(t)&&dated(t)).map(t=>[t.id,esc(t.title)+'<small>'+t.priority+'</small>',t.date,rn(t.region),esc(an(t.agent)),t.owner?esc(sn(t.owner)):'未分配',t.status,act(t.id,'detail-ticket','详情')+act(t.id,'process-ticket','处理')]);}
 if(page==='announcements'){desc='后台公告发布及已读记录；不向游戏、微信或其他外部渠道发送。';actions=['hq','regional'].includes(role)?act('','create-announcement','＋ 新建公告'):'';headers=['公告','日期','适用区域','状态','版本','阅读','操作'];rows=db.announcements.filter(n=>announcementVisible(n)&&dated(n)).map(n=>[esc(n.title),n.date,n.regions.filter(r=>scope().includes(r)).map(rn).join('、'),n.status,'V'+n.version,db.read.includes(actorId()+':'+n.id+':'+n.version)?'已读':'未读',act(n.id,'detail-announcement','查看')+(n.status==='草稿'&&(role==='hq'||n.creator===actorId())?act(n.id,'publish-announcement','发布'):'')+(n.status==='已发布'&&(role==='hq'||n.creator===actorId())?act(n.id,'withdraw-announcement','撤回'):'')]);}
 if(page==='messages'){desc='站内通知由演示操作生成，只有当前账号可见；不会发送外部消息。';headers=['标题','时间','来源','状态','操作'];rows=db.messages.filter(m=>m.owner===actorId()&&dated(m)&&m.regions.every(r=>scope().includes(r))).map(m=>[esc(m.title),m.date,m.source,db.read.includes(actorId()+':'+m.id)?'已读':'未读',act(m.id,'read-message','标为已读')]);}
 if(page==='tasks'){desc='导入、导出和统计任务记录；演示只展示预检结果和记录，不伪造下载文件。';headers=['任务编号','任务','创建日期','范围','记录数','状态','说明','操作'];rows=db.tasks.filter(t=>ownedTask(t)&&dated(t)).map(t=>[t.id,t.name,t.date,t.regions.map(rn).join('、'),t.count,t.status,esc(t.note),act(t.id,'detail-task','详情')]);actions=canExportSummary()?act('','task-guide','进入摘要导出'):'';}
 if(page==='alerts'){desc='对所选事件检查异常和未关联数据。确认仅标记已关注，不修复原数据或修改资产。';headers=['异常编号','日期','区域','类型','来源','跟进','操作'];rows=alertRecords().map(a=>[a.id,a.date,rn(a.region),a.type,a.source,db.ack.includes(actorId()+':'+a.id)?'已关注':'待关注',act(a.id,'ack-alert','确认关注')]);}
 if(page==='sync'){desc=role==='hq'?'虚构接口状态，展示正常、延迟和待核对；没有真实接口、密钥或重试动作。':'仅显示负责区域数据完整性，不提供接口或重试权限。';headers=['区域','数据来源','最近成功','状态','问题','操作'];rows=scope().map((r,i)=>[rn(r),'代理 / 茶馆 / 订单 / 对局','2026-10-10 18:00',i===2?'待核对':'示例完整',i===2?'历史区域快照缺失':'无',act(r,'sync-detail','查看说明')]);}
 if(page==='access'){desc='总部查全后台，其他身份仅查本人。记录为虚构示例，不代表真实身份验证。';headers=['记录编号','账号','时间','结果','浏览器','来源','原因'];rows=db.access.filter(a=>(role==='hq'||a.owner===actorId())&&dated(a)).map(a=>[a.id,a.owner,a.time,a.result,a.device,a.source,a.reason]);}
 if(page==='config'){desc='总部维护服务规则，负责人只读。演示配置用于本浏览器，不改游戏、价格、资产或权限。';headers=['配置','当前值','用途','权限','操作'];rows=[['服务时间',db.config.serviceHours,'工单服务时间说明','总部编辑',role==='hq'?act('serviceHours','edit-config','修改'):'只读'],['普通工单首次响应',db.config.responseHours+' 小时','新工单服务说明','总部编辑',role==='hq'?act('responseHours','edit-config','修改'):'只读'],['普通工单处理期限',db.config.resolveDays+' 工作日','新工单服务说明','总部编辑',role==='hq'?act('resolveDays','edit-config','修改'):'只读'],['低活跃房间阈值',db.config.lowRooms+' 个有效房间','经营分析的低活跃分层','总部编辑',role==='hq'?act('lowRooms','edit-config','修改'):'只读']];}
 return heading(labels[page],desc,actions)+controls()+table(headers,rows);
}
function canExportSummary(){return ['hq','regional','service'].includes(role);}
function alertRecords(){return [...rooms().filter(g=>g.status==='异常').map(g=>({id:'AL-'+g.id,date:g.date,region:g.region,type:'房间异常待核对',source:g.id})),...charges().filter(c=>!c.tea).map(c=>({id:'AL-'+c.id,date:c.date,region:c.region,type:'充值未关联茶馆',source:c.id}))];}
function analysisPage(){const agents=db.agents.filter(currentAgent),active=new Set(rooms().filter(g=>g.status==='已结算').map(g=>g.agent)),low=agents.filter(a=>{const n=rooms().filter(g=>g.agent===a.id&&g.status==='已结算').length;return n>0&&n<db.config.lowRooms}),s=stats();return heading('经营分析与跟进','按同一期间分析授权对象，低活跃分层不自动停用或改变资产。')+controls()+`<div class="stats">${[['当前可见代理',agents.length],['当期有对局代理',agents.filter(a=>active.has(a.id)).length],['当期无对局代理',agents.filter(a=>!active.has(a.id)).length],['低活跃代理',low.length]].map(([t,n])=>`<section class="stat"><div class="stat-label">${t}</div><div class="stat-value">${n}</div><div class="stat-foot">低活跃：有效房间低于 ${db.config.lowRooms} 个</div></section>`).join('')}</div><section class="panel policy"><h2>本次期间摘要</h2><p>净业绩 ${money(s.net)}，有效房间 ${s.games} 个，跨区域去重玩家 ${s.active} 人。无法关联茶馆的充值保留在代理未关联金额中。</p><p>新增、留存和月目标是文档中的扩展方案；本演示没有完整首局历史和目标配置，不生成推测数据。</p></section>`+table(['区域','代理数量','当期活跃代理','有效房间','去重玩家','净业绩','异常线索'],scope().map(r=>{const a=agents.filter(a=>a.region===r),g=rooms().filter(g=>g.region===r&&g.status==='已结算'),t=stats(r);return [rn(r),a.length,uniq(g.map(g=>g.agent)),t.games,t.active,money(t.net),alertRecords().filter(x=>x.region===r).length]}));}
function extensionAction(type,id){
 const known=['create-ticket','detail-ticket','process-ticket','create-announcement','detail-announcement','publish-announcement','withdraw-announcement','read-message','detail-task','task-guide','ack-alert','sync-detail','edit-config'];if(!known.includes(type))return false;
 const ticket=db.tickets.find(t=>t.id===id&&ticketVisible(t)),notice=db.announcements.find(n=>n.id===id&&announcementVisible(n));
 const message=(owner,title,regions,source)=>db.messages.unshift({id:'MSG'+Date.now()+Math.random().toString(36).slice(2,5),owner,title,regions:[...regions],source,date:extDate()});
 if(type==='create-ticket'){const as=db.agents.filter(extAgentVisible);if(!as.length){notify('当前范围没有可服务代理');return true;}modal('新建内部工单',field('ticket-title','工单标题')+`<label for="ticket-agent">关联普通代理</label><select id="ticket-agent" name="ticket-agent">${as.map(a=>`<option value="${a.id}">${esc(a.name)} · ${rn(a.region)}</option>`).join('')}</select><label for="priority">优先级</label><select id="priority" name="priority"><option>普通</option><option>紧急</option></select>`+extText('ticket-body','问题描述'),(f,d)=>{const title=f.get('ticket-title').trim(),body=f.get('ticket-body').trim(),a=as.find(a=>a.id===f.get('ticket-agent')&&extAgentVisible(a));if(title.length<2)return invalid('ticket-title','标题至少2个字');if(body.length<2)return invalid('ticket-body','请填写至少2个字的问题描述');if(!a)return invalid('ticket-agent','对象权限已变化');db.tickets.unshift({id:'TK'+Date.now(),title,description:body,region:a.region,agent:a.id,creator:actorId(),owner:'',date:extDate(),status:'待分配',priority:f.get('priority'),responseHours:db.config.responseHours,resolveDays:db.config.resolveDays,comments:[]});d.close();save('新建内部工单 '+title,[a.region]);notify('工单已创建，等待分配')});return true;}
 if(type==='detail-ticket'&&ticket){modal('工单 '+ticket.id,`<h3>${esc(ticket.title)}</h3><p>${esc(ticket.description)}</p><p>${rn(ticket.region)} · ${ticket.status} · ${ticket.priority}</p><p>创建时服务规则：首次响应 ${ticket.responseHours??24} 小时，处理 ${ticket.resolveDays??3} 个工作日。演示不运行自动时限提醒。</p><h3>处理记录</h3>${ticket.comments.map(c=>`<p>${esc(c.actor)} · ${c.date}<br>${esc(c.body)}</p>`).join('')||'<p>暂无处理记录</p>'}`,null);return true;}
 if(type==='process-ticket'&&ticket){const canAssign=['hq','regional'].includes(role),options=db.services.filter(s=>s.status==='启用'&&(s.region===ticket.region||(s.type==='总部客服'&&role==='hq'&&db.agents.find(a=>a.id===ticket.agent)?.service===s.id)));modal('处理工单 '+ticket.id,`<p>${esc(ticket.title)} · ${rn(ticket.region)}</p>${canAssign?`<label for="ticket-owner">分配客服</label><select id="ticket-owner" name="ticket-owner"><option value="">暂未分配</option>${options.map(s=>`<option value="${s.id}" ${s.id===ticket.owner?'selected':''}>${esc(s.name)}</option>`).join('')}</select>`:''}<label for="ticket-status">处理状态</label><select id="ticket-status" name="ticket-status">${nextTicketStates(ticket).map(s=>`<option ${s===ticket.status?'selected':''}>${s}</option>`).join('')}</select>`+extText('ticket-reply','处理说明'),(f,d)=>{if(!ticketVisible(ticket))return invalid('ticket-reply','对象权限已变化');const body=f.get('ticket-reply').trim(),status=f.get('ticket-status'),owner=canAssign?f.get('ticket-owner'):ticket.owner;if(body.length<2)return invalid('ticket-reply','请填写至少2个字的处理说明');if(!nextTicketStates(ticket).includes(status))return invalid('ticket-status','当前状态不允许此流转');if(status!=='待分配'&&!owner)return invalid('ticket-owner','请先分配有效客服');if(owner&&canAssign&&!options.some(s=>s.id===owner))return invalid('ticket-owner','请选择本区有效客服');if(['service','local'].includes(role)&&ticket.owner!==actorId())return invalid('ticket-reply','客服仅可处理分配给本人的工单');if(status==='已关闭'&&!['hq'].includes(role)&&ticket.creator!==actorId())return invalid('ticket-status','创建人或总部可关闭工单');ticket.owner=owner;ticket.status=status;ticket.comments.push({actor:actorName(),date:extDate(),body});if(owner)message(owner,'工单更新：'+ticket.title,[ticket.region],'客服工单');d.close();save('处理工单 '+ticket.id+' '+status,[ticket.region]);notify('处理意见和状态已保存')});return true;}
 if(type==='create-announcement'&&['hq','regional'].includes(role)){if(!scope().length){notify('没有可发布区域');return true;}modal('新建后台公告草稿',field('notice-title','公告标题')+extRegionSelect()+extText('notice-body','公告正文'),(f,d)=>{const title=f.get('notice-title').trim(),body=f.get('notice-body').trim(),r=f.get('ext-region');if(title.length<2)return invalid('notice-title','标题至少2个字');if(body.length<2)return invalid('notice-body','请填写正文');if(!scope().includes(r))return invalid('ext-region','区域权限已变化');db.announcements.unshift({id:'N'+Date.now(),title,body,regions:[r],creator:actorId(),date:extDate(),status:'草稿',version:1});d.close();save('保存公告草稿 '+title,[r]);notify('草稿已保存，尚未发布')});return true;}
 if(type==='detail-announcement'&&notice){modal(notice.title,`<p>${esc(notice.body)}</p><p>${notice.status} · V${notice.version} · ${notice.regions.filter(r=>scope().includes(r)).map(rn).join('、')}</p><p>仅后台通知，已读不代表同意合同或奖励金额。</p>`,null);if(notice.status==='已发布'){const key=actorId()+':'+notice.id+':'+notice.version;if(!db.read.includes(key))db.read.push(key);try{localStorage.setItem(keyName(),JSON.stringify(db))}catch{} }return true;}
 if(['publish-announcement','withdraw-announcement'].includes(type)&&notice&&(role==='hq'||(notice.creator===actorId()&&notice.regions.every(r=>scope().includes(r))))){const publish=type==='publish-announcement';if(publish&&notice.status!=='草稿'||!publish&&notice.status!=='已发布')return true;modal(publish?'发布后台公告':'撤回后台公告',`<p>${esc(notice.title)}</p><p>范围：${notice.regions.map(rn).join('、')}。只在演示后台展示。</p>`+(publish?'':extText('withdraw-reason','撤回原因')),(f,d)=>{const reason=publish?'发布':f.get('withdraw-reason').trim();if(reason.length<2)return invalid('withdraw-reason','请填写撤回原因');notice.status=publish?'已发布':'已撤回';notice.reason=reason;d.close();save((publish?'发布':'撤回')+'公告 '+notice.title,notice.regions);notify(publish?'公告已发布到后台演示':'公告已撤回，历史保留')});return true;}
 if(type==='read-message'){const m=db.messages.find(m=>m.id===id&&m.owner===actorId()&&m.regions.every(r=>scope().includes(r)));if(m&&!db.read.includes(actorId()+':'+id)){db.read.push(actorId()+':'+id);save('标记站内消息已读',m.regions)}return true;}
 if(type==='detail-task'){const t=db.tasks.find(t=>t.id===id&&ownedTask(t));if(t)modal('数据任务 '+t.id,`<p>${t.name} · ${t.status}</p><p>${esc(t.note)}</p><p>当前任务为示例记录，无生成文件。真实导出请进入经营总览或获准统计页。</p>`,null);return true;}
 if(type==='task-guide'&&canExportSummary()){navigatePage('overview');notify('请点击导出区域汇总，生成当前筛选条件的CSV');return true;}
 if(type==='ack-alert'){const a=alertRecords().find(a=>a.id===id);if(a&&!db.ack.includes(actorId()+':'+id)){db.ack.push(actorId()+':'+id);save('关注异常 '+id,[a.region]);notify('已标记关注，原始异常数据保持原状态')}return true;}
 if(type==='sync-detail'&&scope().includes(id)){modal('数据同步说明',`<p>${rn(id)}：此处为接口监控示意。</p><p>正式后台应区分同步延迟、权限失败、字段缺失和业务拒绝；写请求超时先核对结果，再以原请求号重试。</p><p>演示不调用真实接口，也不提供充值、转卡或对局补结算。</p>`,null);return true;}
 if(type==='edit-config'&&role==='hq'&&Object.hasOwn(db.config,id)){const text=id==='serviceHours',names={serviceHours:'服务时间',responseHours:'首次响应小时数',resolveDays:'处理工作日数',lowRooms:'低活跃房间阈值'};modal('修改 '+names[id],field('config-value',names[id],db.config[id],text?'text':'number')+extText('config-reason','修改原因'),(f,d)=>{const raw=f.get('config-value').trim(),reason=f.get('config-reason').trim(),v=text?raw:Number(raw);if(text&&!/^\d{2}:\d{2}[–-]\d{2}:\d{2}$/.test(raw))return invalid('config-value','请按09:00–18:00填写服务时间');if(text){const [a,b]=raw.split(/[–-]/),valid=t=>Number(t.slice(0,2))<24&&Number(t.slice(3))<60;if(!valid(a)||!valid(b)||a>=b)return invalid('config-value','时间须有效且开始早于结束');}if(!text&&(!/^\d+$/.test(raw)||v<1||v>999))return invalid('config-value','请输入1至999的整数');if(reason.length<2)return invalid('config-reason','请填写修改原因');db.config[id]=v;d.close();save('修改 '+names[id]+'：'+raw+'；原因：'+reason);notify('演示配置已保存')});return true;}
 notify('当前对象或操作不在权限范围');return true;
}
function keyName(){return key;}
render();
